Sort primary keys of ClangFormat configuration
The output from the `clang-format --dump-config` command is compared against Arduino's configuration file to check for
additions, removals, or type changes resulting from updating to a new version of ClangFormat. The expectation is that
any diff represents a change in the tool which must be evaluated before updating the configuration file contents to
match the new output.

Although it seems some attempt was made at sorting the output in alphabetical order, it is not completely consistent. It
turns out that arbitrary changes to the order of the keys may occur from one version to another, resulting in spurious
diffs or difficult to read valid diffs. The solution is to sort the keys from the dumped output in a consistent order.
This is done using the excellent yq tool.

In addition to avoiding problematic diffs, this will make the configuration file easier to use.

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -231,6 +231,12 @@ tasks:
       - task: clang-format:check-installed
     cmds:
       - |
+        if ! which yq &>/dev/null; then
+          echo "ec not found or not in PATH. Please install: https://github.com/mikefarah/yq/#install"
+          exit 1
+        fi
+
+      - |
         # Add source comment
         echo \
           "# Source: https://github.com/arduino/tooling-project-assets/tree/main/other/clang-format-configuration" > \
@@ -241,6 +247,10 @@ tasks:
           --dump-config \
           --style=file:"{{.CLANG_FORMAT_CONFIGURATION_PATH}}" >> \
             "{{.TARGET_PATH}}"
+
+      - |
+        # Fix the inconsistent key order
+        yq --inplace 'sort_keys(.)' "{{.TARGET_PATH}}"
 
   # Use ClangFormat to format the files under the path specified by TARGET_FOLDER recursively
   clang-format:format:
@@ -272,10 +282,14 @@ tasks:
 
   clang-format:update-config:
     desc: Update ClangFormat configuration file to match effective tool configuration
+    vars:
+      WORKING_PATH:
+        sh: task utility:mktemp-file TEMPLATE="clang-format-update-config-XXXXXXXXXX.json"
     cmds:
       - task: clang-format:dump-config
         vars:
-          TARGET_PATH: "{{.CLANG_FORMAT_CONFIGURATION_PATH}}"
+          TARGET_PATH: "{{.WORKING_PATH}}"
+      - mv --force "{{.WORKING_PATH}}" "{{.CLANG_FORMAT_CONFIGURATION_PATH}}"
 
   clang-format:update-golden:
     desc: Update golden master test data for current configuration
