Use taskfile variable to define primary Go module path
Although support was added to the Go module related "templates" for projects which contain modules at other paths, the
assumption remained that there will always be a primary module in the root of the repository, and this path was hardcoded
at several locations in the taskfiles.

It might be that a project that is not a Go module contains an accessory Go module in a subfolder. In this case, the use
of a taskfile variable will allow that path to be defined in one place, avoiding the need to override the hardcoded
incorrect location whenever a Go module-related task is run manually.

diff --git a/workflow-templates/assets/go-task/Taskfile.yml b/workflow-templates/assets/go-task/Taskfile.yml
--- a/workflow-templates/assets/go-task/Taskfile.yml
+++ b/workflow-templates/assets/go-task/Taskfile.yml
@@ -2,14 +2,17 @@
 version: "3"
 
 vars:
+  # Path of the project's primary Go module:
+  DEFAULT_GO_MODULE_PATH: ./
   DEFAULT_GO_PACKAGES:
     sh: |
-      echo $(cd {{default "./" .GO_MODULE_PATH}} && go list ./... | tr '\n' ' ' || echo '"ERROR: Unable to discover Go packages"')
+      echo $(cd {{default .DEFAULT_GO_MODULE_PATH .GO_MODULE_PATH}} && go list ./... | tr '\n' ' ' || echo '"ERROR: Unable to discover Go packages"')
   LDFLAGS:
 
 tasks:
   # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/go-task/Taskfile.yml
   go:build:
     desc: Build the Go code
+    dir: "{{.DEFAULT_GO_MODULE_PATH}}"
     cmds:
       - go build -v {{.LDFLAGS}}
